[package]
name = "hypersignrs"
version = "0.1.0"
authors = ["rujak"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = "0.9.0"
ed25519-dalek = "1.0.0"
rand = "0.7.3"
